### ISSUE TITLE
feature: we can add more go origin from other language

### ISSUE THREAD

**Issue by yangwenmai** [golang-design/history#11]
## The origins of Go

1.  Thefirs twas  cal le dSque ak (‘‘Alangu agefor  communic atingwit hmice’’),  whichprovide dalan-gu agefor  handlingmou seand  key board  events,  with statically created channels
2. The Plan9 operating system carried these ideas forward in a language called Alef.
3. iota is  loosely  from APL

From: https://www.gopl.io/ch1.pdf

![image](https://user-images.githubusercontent.com/1710912/93153709-74504880-f734-11ea-8faa-9d8edb97015c.png)

## Go 语言的起源

1. 第一次尝试引入CSP特性的编程语言叫Squeak（老鼠间交流的语言），是一个提供鼠标和键盘事件处理的编程语言，它的管道是静态创建的。
2. Newsqueak是一个带垃圾回收的纯函数式语言，它再次针对键盘、鼠标和窗口事件管理。
3. 在Plan9操作系统中，这些优秀的想法被吸收到了一个叫Alef的编程语言中。Alef试图将Newsqueak语言改造为系统编程语言，但是因为缺少垃圾回收机制而导致并发编程很痛苦。
4. iota语法是从APL语言借鉴，词法作用域与嵌套函数来自于Scheme语言（和其他很多语言）

摘录：https://books.studygolang.com/gopl-zh/ch0/ch0-01.html

we can dig more about the origin of Go and list this code compare.

**Comment by changkun** [comment]
This is covered in **talk/rob2010b**
