### ISSUE TITLE
feature: go package management timeline(with gopath godep govendor go modules etc.)

### ISSUE THREAD

**Issue by yangwenmai** [golang-design/history#12]
Can we add all go package management history with tools or repos or discussion.

Such as:

![image](https://user-images.githubusercontent.com/1710912/93154611-a4005000-f736-11ea-9dc2-071f36d8b631.png)

## References

https://github.com/golang/go/wiki/PackageManagementTools

**Comment by changkun** [comment]
Interesting. I think go modules is the official tool and godep is one of the iconic tools from the community, which is enough for history. Maybe it is interesting for everyone so.

The issue leads to another question regarding how should we organize the timeline. For now, the timeline is reflected in the date of an item, but hard to identify.

**Comment by changkun** [comment]
@yangwenmai

**Comment by changkun** [comment]
As reasons said above, closing...
