### ISSUE TITLE
feature: performance is not important under circumstances

### ISSUE THREAD

**Issue by yangwenmai** [golang-design/history#14]
I found https://github.com/golang/go/issues/24499, and wrote a [blog article](https://maiyang.me/post/2020-02-05-image-jpeg-decode-is-slow/) about it.

>@nigeltao : Amongst other things, standard library code is often read by people learning Go, so for that code, we favor simplicity and readability over raw performance more than what other Go packages choose. Neither position is wrong, just a different trade-off.

Maybe we can find more issues.

**Comment by changkun** [comment]
The issue 24499 is already on my reading list. I think we can separate the feature into two parts:

1. When performance improvement is not preferred for the change?
2. What are the friends of the '`jpeg.Decode` is slow' issue?

**Comment by yangwenmai** [comment]
I agree.

**Comment by changkun** [comment]
A recent discovered feature relates to the change of MADV_DONTNEED to MADV_FREE in go 1.12-1.15, and the recent fall back in go 1.16.

See 270a64e163427bd9ab87e9f0650962967e180881 for more details.

**Comment by changkun** [comment]
I think we will just gradually update the list and this feature request is somewhat not as interesting as classifying by functionality. One can always read the related links and figure out what change fits this case. There is no strong need for listing all of them in a separate section. Thus, close.
