### ISSUE TITLE
document the history of blank identifier to ignore values

### ISSUE THREAD

**Issue by Delta456** [golang-design/history#16]
I think its necessary to know and research why `_` was specifically chosen as the identifier to ignore values as Go was the first one to adopt it.

**Comment by changkun** [comment]
The blank identifier was introduced in https://github.com/golang/go/commit/4e56b33b42bb524f2b80bc1bded1d42bc98c4bd9.

The language spec states the reason why it was chosen:

> The blank identifier provides a convenient way to ignore values returned by a multi-valued expression [...]

Go is not the first programming language that adopts it. I know the blank identifier way back from Python 2.6, giving the fact that Python 2.6 was released in 2008 and the change of Go was in 2009. 

So I do not think the blank identifier could get into the repo as a fascinating history. This seems like a likely decline. Leave one week for comments.

**Comment by Delta456** [comment]
But `_` is a valid identifier in Python i.e. you can use  and change it. Go and other languages who have it treat them very specially unlike others.

**Comment by changkun** [comment]
It's just a matter of choice. The semantics are similar.

If you'd like to object the argument, you need to present more concrete reasons such as how a blank identifier is as interesting as the `go` keyword.

**Comment by changkun** [comment]
No changes in consensus. Close.
