### ISSUE TITLE
https://golang.design/history have HTTP 400 Error

### ISSUE THREAD

**Issue by yangwenmai** [golang-design/history#30]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/1710912/168479315-f7114289-a644-429e-9a8c-ff84c8f7315b.png">

**Comment by changkun** [comment]
Of course, the badge will be 400 since it is not from GitHub source anymore.

This is an intended behavior, and I don't think showing a page count mean anything to the reader. 

If you are interested, visit here https://changkun.de/urlstat/dashboard
